---
language: generic

matrix:
  include:
    - os: linux
      env: PYTHON=2.7
    - os: osx
      env: PYTHON=2.7

env:
  global:
    - PACKAGE_NAME=omero-web
    - REQUIREMENTS_CHANNEL=manics
    - PATH="$HOME/miniconda/bin:$PATH"

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
        wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda && rm miniconda.sh
  - conda install -y conda-build anaconda-client
  - conda info -a

script:
  # Override the version string for dev builds
  - if [ -z "${TRAVIS_TAG}" ]; then
      export VERSION_SUFFIX=".${TRAVIS_BRANCH}";
    else
      export VERSION_SUFFIX="";
    fi
  - conda build -c ${REQUIREMENTS_CHANNEL} --python $PYTHON .

deploy:
  - provider: script
    skip_cleanup: true
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload $HOME/miniconda/conda-bld/noarch/$PACKAGE_NAME-*.tar.bz2 --force -l testing
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: script
    skip_cleanup: true
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload $HOME/miniconda/conda-bld/noarch/$PACKAGE_NAME-*.tar.bz2
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
