{% set name = "omero-web" %}
{% set version = "5.5.dev2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11d032562484eb88577de4ba18bc98af4466a6a13e73589c680a1d6ae2a4368f

build:
  noarch: python
  number: 0
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python =2.7
  run:
    - django =1.8
    - django-pipeline =1.3.20
    - gunicorn >=19.3
    - omero-marshal =0.6
    - omero-py =5.5
    - pillow
    - python =2.7

test:
  commands:
    - omero-web --help
    - omero-web web --help
    - omero-web web status
    - omero-web web diagnostics
    - omero-web web config nginx
  imports:
    # - omeroweb
    # - omeroweb.api
    # - omeroweb.feedback
    # - omeroweb.feedback.templatetags
    # - omeroweb.webadmin
    # - omeroweb.webadmin.templatetags
    # - omeroweb.webclient
    # - omeroweb.webclient.controller
    # - omeroweb.webclient.templatetags
    # - omeroweb.webgateway
    # - omeroweb.webgateway.templatetags
    # - omeroweb.webredirect

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: OMERO.web
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-web

extra:
  recipe-maintainers:
    - ome
