{% set name = "omero-web" %}
{% set version = "5.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 564ecde0533da01fc561a11c7e8b1cb23ce5e8d21ce8db8f6f89433de9818a00

build:
  noarch: python
  number: 1
  script: "python -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python =3
  run:
    - django =1.11
    - django-pipeline =1.7
    - gunicorn >=19.3
    - omero-marshal =0.7
    - omero-py =5.6
    - python =3

outputs:
  - name: omero-web
    build:
      noarch: python
    test:
      commands:
        - omero web --help
      imports:
        - omeroweb
        - omeroweb.api
        - omeroweb.feedback
        # - omeroweb.feedback.templatetags
        - omeroweb.webadmin
        # - omeroweb.webadmin.templatetags
        - omeroweb.webclient
        # - omeroweb.webclient.controller
        # - omeroweb.webclient.templatetags
        - omeroweb.webgateway
        # - omeroweb.webgateway.templatetags
        - omeroweb.webredirect
  - name: omero-web-server
    build:
      noarch: python
    script: build-wrapper.sh
    requirements:
      host:
        - python =3
      run:
        - {{ pin_subpackage('omero-web', exact=True) }}
    test:
      commands:
        - omero-web --help
        - omero-web config get
        - omero-web web --help
        - omero-web web diagnostics
        - omero-web web config nginx
        - omero-web status

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: OMERO.web
  description: |
    omero-web: OMERO.web Python library.
    omero-web-server: wrapper script for starting and stopping OMERO.web.
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-web

extra:
  recipe-maintainers:
    - ome
